### ISSUE TITLE
No web UI to create projects?

### ISSUE THREAD

**Issue by bootstraponline** [TestArmada/admiral2#24]
<img width="860" alt="no-create-projects" src="https://cloud.githubusercontent.com/assets/1173057/26731724/efa202cc-4782-11e7-89c5-bff13323596a.png">

**Comment by archlichking** [comment]
Admiral2 doesn't require UI to create new project. Project will be created on the fly when magellan-admiral2-plugin is in use.

**Comment by bootstraponline** [comment]
Ok, thanks for explaining.
